### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cshaa** [li-dennis/TesseRift#6]
Hi, it's me again.
I'd like to use the `hypercube` code in my school project. I will probably rewrite it completely but I'd like to mark TesseRift as the source. To do that, however, I'd need some sort of an open-source license. Would you mind adding a LICENSE file with MIT or BSD style license?
Thanks again, this is the best tesseract projection on the Internet I've found so far.
m93a.

**Comment by li-dennis** [comment]
Done :)

Good luck with your project!

**Comment by cshaa** [comment]
Neat! Thanks :)
